package Client.Picker;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Client.GraphicClientEndConnector;
import Client.RoomReservationClient;
import com.github.lgooddatepicker.components.DateTimePicker;
import com.github.lgooddatepicker.optionalusertools.DateTimeChangeListener;
import com.github.lgooddatepicker.zinternaltools.DateTimeChangeEvent;
import org.jdesktop.swingx.JXDatePicker;
import org.xml.sax.SAXException;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.xml.transform.TransformerException;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author emil
 */
public class Picker extends javax.swing.JFrame {

    /**
     * Creates new form Picker
     */
    public Picker() {
        super("Floor Picker");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        floorPicker = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        month = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        newDuration = new javax.swing.JLabel();
        duration = new javax.swing.JTextField();
        datePicker = new DateTimePicker();
        datePicker.setForeground(Color.WHITE);
        floorPicker.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                floorPickerItemStateChanged(evt);
            }
        });
        floorPicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    floorPickerActionPerformed(evt);
                } catch (TransformerException e) {
                    e.printStackTrace();
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (SAXException e) {
                    e.printStackTrace();
                }
            }
        });
        datePicker.setDateTimePermissive(LocalDateTime.now());
        jLabel1.setText("Floor");
        newDuration.setText("Duration of Reservation");
        duration.setText("30");
        month.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.MINUTE));
        duration.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                dateChange();
            }


        });

        jLabel2.setText("Date and Time");

        datePicker.addDateTimeChangeListener(new DateTimeChangeListener() {
            @Override
            public void dateOrTimeChanged(DateTimeChangeEvent dateTimeChangeEvent) {
                dateChange();
            }
        }
    );



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(floorPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(duration))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(newDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floorPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(duration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void centralChangeHandler() throws TransformerException, IOException, SAXException {
        //TODO
        Integer newValue = floorPicker.getItemAt(floorPicker.getSelectedIndex());
        dateChange();
        System.out.println("Changing floor to:" + newValue);
        GraphicClientEndConnector.setCurrentFloor(newValue);

    }
    
    private void floorPickerActionPerformed(java.awt.event.ActionEvent evt) throws TransformerException, IOException, SAXException {//GEN-FIRST:event_floorPickerActionPerformed
        centralChangeHandler();
        
    }//GEN-LAST:event_floorPickerActionPerformed

    private void dateChange(){
        LocalDateTime newDate = datePicker.getDateTimePermissive();
        LocalDate checkDate = datePicker.getDatePicker().getDate();
        LocalTime checkTime = datePicker.getTimePicker().getTime();
        if (newDate == null || checkDate == null || checkTime == null) return;
        DateTimeFormatter formatDate = DateTimeFormatter.ofPattern("MM dd yyyy HH mm");
        String dateStr = formatDate.format(newDate);
        String[] dateInfo = dateStr.split(" ");
        GraphicClientEndConnector.changeTime(Integer.parseInt(dateInfo[0]), Integer.parseInt(dateInfo[1]),
                                        Integer.parseInt(dateInfo[2]), Integer.parseInt(dateInfo[3]), Integer.parseInt(dateInfo[4]), Integer.parseInt(duration.getText()));

    }//GEN-LAST:event_monthStateChanged
//        Object date = month.getValue();
//        if (date instanceof Date){
//            Date newDate = (Date) date;
//            SimpleDateFormat formatDate = new SimpleDateFormat ("MM dd yyyy hh mm");
//            String dateStr = formatDate.format(newDate);
//            String[] dateInfo = dateStr.split(" ");
//            GraphicClientEndConnector.changeTime(Integer.parseInt(dateInfo[0]), Integer.parseInt(dateInfo[1]),
//                                        Integer.parseInt(dateInfo[2]), Integer.parseInt(dateInfo[3]), Integer.parseInt(dateInfo[4]), Integer.parseInt(duration.getText()));
//
    private void floorPickerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_floorPickerItemStateChanged
    }//GEN-LAST:event_floorPickerItemStateChanged

    /**
     * //@param args the command line arguments
     */

    private void durationActionPerformed(ActionEvent evt){

        System.out.println("A");
        dateChange();
    }

    public void clear(){
        this.floorPicker.removeAll();
    }

    public void stop(){
        dispose();
    }

    public void addChoice(Integer floorCount){
        this.floorPicker.addItem(floorCount);
    }
    public static void runner(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Picker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Picker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Picker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Picker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Picker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField duration;
    private DateTimePicker endDatePicker;
    private javax.swing.JComboBox<Integer> floorPicker;
    private DateTimePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner month;
    private javax.swing.JLabel newDuration;
    // End of variables declaration//GEN-END:variables
}
